# test that the to_matrix function of the circuit is matching the circuit_to_mpo function.
# expected behavior: the matrix generated by the circuit should be equal to the matrix generated from the MPO_circuit.
import rqcopt_mpo.jax_config

import jax.numpy as jnp
from rqcopt_mpo.circuit.circuit_builder import generate_random_circuit
from rqcopt_mpo.mpo.mpo_builder import circuit_to_mpo

n_sites = 5
seed = 42
random_circuit = generate_random_circuit(
    n_sites=n_sites,
    n_layers=40,
    p_single=0.3,
    p_two=0.3,
    seed=seed,
    gate_name_single='U1',
    gate_name_two='U2',
    dtype=jnp.complex128
    )

random_circuit.print_gates()

random_circuit_matrix = random_circuit.to_matrix()
random_circuit_matrix_from_mpo = circuit_to_mpo(random_circuit).to_matrix()

jnp.allclose(random_circuit_matrix, random_circuit_matrix_from_mpo, rtol=1e-5, atol=1e-13)
print("Circuit to matrix = Circuit to MPO to matrix")



