hamiltonian: heisenberg
n_sites: 6
degree: 2
n_repetitions: 1
n_id_layers: 0
t: 0.25
disordered: false
load: false
load_reference: true
normalize_reference: true
ref_nbr: 1
lr: 5e-3
n_iter: 100
optimizer: ADAM
max_bondim: 128